### ISSUE TITLE
Wordpress environment

### ISSUE THREAD

**Issue by karneaud** [mkudenko/vagrant-ansible-php7#7]
I have used wordpress and ansible before. Would it be possible to incorporate WP into the fold?

**Comment by mkudenko** [comment]
@karneaud I recommend using Laravel Homestead.

**Comment by karneaud** [comment]
@mkudenko Homestead is ok but I wanted to have a global automation but be able to individualize each site using a custom yml for each. Your library seems to be setup just right to do such.
